org.gradle.daemon=true
org.gradle.jvmargs=-Xms128m -Xmx1500m
org.gradle.configureondemand=false
android.enableR8.fullMode=true
android.useAndroidX=true
android.enableJetifier=false
android.defaults.buildfeatures.resvalues=false
android.sdk.defaultTargetSdkToCompileSdkIfUnset=true
android.enableAppCompileTimeRClass=true
android.usesSdkInManifest.disallowed=true
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=true
android.builtInKotlin=true
android.newDsl=true
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false